---
title: "Lab 10"
author: "Vignesh Narayanaswamy"
date: "4/2/2020"
output: html_document
---

```{r, warning=FALSE, results='hide', message=FALSE}
library(tidyverse)
library(maps)
library(mapdata)
library(lubridate)
library(viridis)
library(wesanderson)
library(plotly)
library(ggplot2)
library(gganimate)
library(transformr)
library(gifski)
```

## Mapping data to shapes

### COVID19-related confirmed deaths in the US

```{r, warning=FALSE, results='hide', message=FALSE}
daily_report <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/04-01-2020.csv")) %>% rename(Long = "Long_") %>% filter(Country_Region == "US") %>% group_by(Province_State) %>% summarize(Deaths = sum(Deaths)) %>% mutate(Province_State = tolower(Province_State))
```

```{r, warning=FALSE}
# loading the US map
us <- map_data("state")
state_join <- left_join(us, daily_report, by = c("region" = "Province_State"))

# plotting map and adding data layer
ggplot(data = us, mapping = aes(x = long, y = lat, group = group)) + coord_fixed(1.3) + geom_polygon(data = state_join, aes(fill = Deaths), color = "white") + geom_polygon(color = "black", fill = NA) + scale_fill_gradientn(colours = wes_palette("Zissou1", 100, type = "continuous"), trans = "log10") + labs(title = "COVID-19 deaths in the US")
```

## Interactive graph

### COVID19-related deaths in the state of Washington

```{r, warning=FALSE, results='hide', message=FALSE}
daily_report <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/04-01-2020.csv")) %>% rename(Long = "Long_") %>% filter(Province_State == "New York") %>% group_by(Admin2) %>% summarize(Deaths = sum(Deaths)) %>% mutate(Admin2 = tolower(Admin2))
```

```{r, warning=FALSE}
us <- map_data("state")
ny_us <- subset(us, region == "new york")
counties <- map_data("county")
ny_county <- subset(counties, region == "new york")
state_join <- left_join(ny_county, daily_report, by = c("subregion" = "Admin2"))

ggplotly(ggplot(data = ny_county, mapping = aes(x = long, y = lat, group = group)) + coord_fixed(1.3) + geom_polygon(data = state_join, aes(fill = Deaths), color = "black") + scale_fill_gradientn(colours = wes_palette("Zissou1", 100, type = "continuous")) + ggtitle("COVID-19 deaths in NY") + labs(x=NULL, y=NULL) + theme(panel.border = element_blank()) + theme(panel.background = element_blank()) + theme(axis.ticks = element_blank()) + theme(axis.text = element_blank()))
```

## Graphs with animation

### Comparing confirmed cases and deaths between countries

```{r, warning=FALSE}

# getting the time series data for confirmed cases

time_series_confirmed <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")) %>% rename(Province_State = "Province/State", Country_Region = "Country/Region")  %>% pivot_longer(-c(Province_State, Country_Region, Lat, Long), names_to = "Date", values_to = "Confirmed")

# getting the time series data for deaths

time_series_deaths_long <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")) %>% rename(Province_State = "Province/State", Country_Region = "Country/Region")  %>% pivot_longer(-c(Province_State, Country_Region, Lat, Long), names_to = "Date", values_to = "Deaths")

# create keys

time_series_confirmed <- time_series_confirmed %>% unite(Key, Province_State, Country_Region, Date, sep = ".", remove = FALSE)

time_series_deaths_long <- time_series_deaths_long %>% unite(Key, Province_State, Country_Region, Date, sep = ".") %>% select(Key, Deaths)

# join tables

time_series_long_joined <- full_join(time_series_confirmed, time_series_deaths_long, by = c("Key"))

time_series_long_joined <- time_series_long_joined %>% select(-Key)

# reformat the data

time_series_long_joined$Date <- mdy(time_series_long_joined$Date)

# create report table with counts

time_series_long_joined_counts <- time_series_long_joined %>% pivot_longer(-c(Province_State, Country_Region, Lat, Long, Date), names_to = "Report_Type", values_to = "Counts")

# generating the animation

data_time <- time_series_long_joined_counts %>% group_by(Country_Region,Date) %>% filter (Country_Region %in% c("Korea, South", "Japan", "India","Spain","Italy","US"))

p <- ggplot(data_time, aes(x = Date, y = log2(Counts), fill = Report_Type, color = Report_Type)) + geom_point() + geom_line() + ggtitle("COVID-19 confirmed cases and associated Deaths") + geom_point(aes(group = seq_along(Date))) + transition_reveal(Date) + facet_wrap(~Country_Region, ncol=2, scales="free_y")

animate(p,renderer = gifski_renderer(), end_pause = 15)
```

